### ISSUE TITLE
it's very laggy

### ISSUE THREAD

**Issue by viethungspy** [sublimelsp/LSP-tailwindcss#17] opened 2021-07-16 10:12 UTC
I don't know if it's the problem with my machine.
When writing and deleting it will delay from a few hundred seconds to a few seconds to display the content.
Is there a way when writing, can write all the content and load the suggestion after stopping writing, and when deleting do nothing.
I'm a Fan of fast sublime text.

https://user-images.githubusercontent.com/33823245/125932176-ff3e66a1-8992-4a20-b7cb-9723cca90c01.mp4

**Comment by davidwebca** [comment] 2021-07-16 11:00
Personaly I don't have the same problem here, but I have a cranked up Macbook Pro so I'm not a reference.

**Comment by predragnikolic** [comment] 2021-07-16 15:52
I cannot seem to reproduce this.

Can you provide the contents of your `tailwind.config.js` file?
----
Also, can you try with another project to see if the lag is happening there also?
Here is one tailwindcss project that works fine on my end:
```
git clone https://github.com/ParamagicDev/tailwind-example
cd tailwind-example 
npm i 
subl . 
```

**Comment by predragnikolic** [comment] 2021-07-16 15:56
And just to confirm, 
The lag is gone when you disable the `LSP-tailwindcss` plugin from the command palette with  `Package Control: Disable Package`?

**Comment by viet-hung-it** [comment] 2021-07-17 10:13
I am sure that when I disable lsp-tailwind there is no delay anymore.

When I was still using sublime text 3 I installed tailwind CSS Autocomplete and also got a slight delay, I reinstalled sublime text 4 and installed lsp-tailwind and it felt so delayed that it was unusable.

Is it because my configuration is too weak, I only have 8Gb of ram.

**Comment by predragnikolic** [comment] 2021-12-12 22:48
I will close this, because I cannot reproduce it.
Feel free to reopen it, but please provide a repro repo.

**Closed by predragnikolic** 2021-12-12 22:48 UTC

**Comment by rchl** [comment] 2021-12-12 22:56
In theory a large numbers of completions could trigger something like that. Happens something to me with typescript server when it's returning ~5000 of completions or more.

**Comment by estudiooka** [comment] 2022-05-10 07:22
disable colors and components you don't need
